App/api/urls.py
# Django Import:
from django.urls import path
from .views import *

urlpatterns = [
    # Device API:
    path('device/all', DeviceAllAPI.as_view(), name='device_all'),

    # Color API:
    path('color/all', ColorAllAPI.as_view(), name='color_all'),
    path('color/add', ColorAddAPI.as_view(), name='color_add'),
]

App/autocli/urls.py
# Django Import:
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include, re_path
from django.contrib import admin
import debug_toolbar

# Application Import:
from administration.views import login_page

# Urls patterns:
urlpatterns = [
    path('', login_page),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += i18n_patterns (
    path('inventory/', include('inventory.urls')),
    path('administration/', include('administration.urls')),
    prefix_default_language=True,
)

App/inventory/models/device.py
# Django Import:
from django.db import models
from django.utils.translation import gettext_lazy as _

# Applications Import:
from ..managers import NotDeleted, ActiveManager
from .icons import ICONS

# Other models Import:
from .credential import Credential


# Model code:
class Device(models.Model):

    # Static values:
    STATUS_CHOICES = (
        (0, _('Nonactive')),
        (1, _('Active')),
    )
    DEVICE_TYPE = (
        (0, _('autodetect')),
        (1, _('cisco_ios')),
        (2, _('cisco_xr')),
        (3, _('cisco_xe')),
        (4, _('cisco_nxos')),
    )

    # Creation values:
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Status values:
    root = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)

    # Device status:
    ssh_status = models.BooleanField(default=False)
    https_status = models.BooleanField(default=False)

    # Main model values:
    name = models.CharField(
        verbose_name=_('Device name'),
        max_length=16,
        blank=False,
        unique=True
    )
    hostname = models.CharField(
        verbose_name=_('IP address'),
        max_length=64,
        blank=False,
        unique=True,
        error_messages={
            'null': _('This field is mandatory.'),
            'blank': _('This field is mandatory.'),
        },
        help_text=_('Enter a valid IP address or DNS resolvable hostname.'),
    )
    device_type = models.IntegerField(
        verbose_name=_('Device type'),
        choices=DEVICE_TYPE,
        default=0
    )
    ico = models.IntegerField(
        verbose_name=_('Device graphic'),
        choices=ICONS,
        default=0
    )
    ssh_port = models.IntegerField(
        verbose_name=_('SSH port'),
        default=22
    )
    https_port = models.IntegerField(
        verbose_name=_('HTTPS port'),
        default=443
    )
    description = models.CharField(
        verbose_name=_('Description'),
        max_length=256,
        default="Device description."
    )

    # Security and credentials:
    credential = models.ForeignKey(Credential, on_delete=models.PROTECT, null=True, blank=True)
    secret = models.CharField(max_length=64, null=True, blank=True)
    token = models.CharField(max_length=128, null=True, blank=True)
    certificate = models.BooleanField(default=False)

    # Object managers:
    objects = NotDeleted()
    active = ActiveManager()

    # Model representation:
    def __str__(self) -> str:
        return self.name

    # Override default Delete method:
    def delete(self):
        """
            Override the default Delete method to see if the device was created by the Root user,
            if true don't change anything, otherwise change deleted value to true.
        """
        # Check if root value is True:
        if self.root == True:
            # Inform the user that the object cannot be deleted because is a root object:
            assert self.pk is not None, (
                f"{self._meta.object_name} object can't be deleted because its a root object.")
        else:
            # Change deleted value to True, to inform that object is deleted:
            self.deleted = True


    # Meta sub class:
    class Meta:
        app_label = 'inventory'
        verbose_name = _('Device')
        verbose_name_plural = _('Devices')


class DeviceData(models.Model):

    # Corelation witch device model:
    device = models.ForeignKey(Device, on_delete=models.CASCADE, null=False, blank=False)

    # Creation data:
    created = models.DateTimeField(auto_now_add=True)

    # Show version output:
    version = models.CharField(max_length=64, blank=True, null=True)
    hostname = models.CharField(max_length=64, blank=True, null=True)
    uptime = models.CharField(max_length=64, blank=True, null=True)
    reload_reason = models.CharField(max_length=64, blank=True, null=True)
    running_image = models.CharField(max_length=64, blank=True, null=True)
    config_register = models.CharField(max_length=64, blank=True, null=True)
    hardware_list = models.JSONField(blank=True, null=True)
    serial_list = models.JSONField(blank=True, null=True)
    mac_list = models.JSONField(blank=True, null=True)

App/inventory/views/test.py
# Django Imports:
from django.utils.translation import gettext_lazy as _
from django.shortcuts import render, get_object_or_404

# Application Import:
from ..tasks import single_device_check

def test(request):
    data = {
        'output': 'RKKR'
    }

    data['output'] = single_device_check(52)
    #data['output'] = single_device_check.delay(52)

    return render(request, 'test.html', data)

App/templates/add_form.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}

    <!-- Grid Form -->
    <div class="grid-box" id="form-grid">
        
        <!-- Form header -->
        <div class="form-header">
            <h3>{{ page_name }}</h3>  
        </div>

        <!-- Form body -->
        <div class="form-body">
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button class="form-button action-button" type="submit" value="Submit">{% translate "Submit" %}</button>
            </form>
        </div>

    </div>

{% endblock %}

App/templates/add_object.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}

    <!-- Grid Form -->
    <div class="grid-box" id="form-grid">
        
        <!-- Form header -->
        <div class="form-header">
            <h3>{{ page_name }}</h3>  
        </div>

        <!-- Form body -->
        <div class="form-body">
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button class="form-button action-button" type="submit" value="Submit">{% translate "Submit" %}</button>
            </form>
        </div>

    </div>

{% endblock %}

App/templates/message.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}


    
{% endblock %}

App/templates/one_object.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load tags %}

{% block content %}

    <!-- Grid container for object items -->
    <div id="object-grid">
                            
        <!-- Single object item -->
        <div class="object-item">
            <div class="object-subitem grid-box">

                <!-- Single model item header -->
                <div class="object-item-header ">
                    <h4>{% translate "Basic information" %}</h4>
                </div>

                <!-- Single model item body -->
                <div class="object-item-body">
                    <table>
                        {% for row in display %}
                            <tr>
                                <th>{{ row|title }}:</th>
                                <td>{{ object|key_value:row }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>

            </div>
        </div>

    </div>
    
{% endblock %}

App/templates/search.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load tags %}

{% block content %}

    {% if grid %}

        <!-- Grid container for models -->
        <div id="model-grid">
            
            {% for object in objects %}
                <!-- Single model item -->
                <div class="model-item">
                    <div class="model-subitem grid-box">

                        <div class="model-item-status">

                            {% if object.status or object.ssh_status or object.https_status %}
                                <!-- Box activity -->
                                <div class="ball-box">
                                    <!-- Active status -->
                                    {% if object.status == 1 %}
                                    <div class="ball ball-active" aria-label="Active"></div>
                                    {% else %}
                                    <div class="ball ball-inactive" aria-label="Active"></div>
                                    {% endif %}
                                    <!-- SSH status -->
                                    {% if object.ssh_status == True %}
                                        <div class="ball ball-active" aria-label="SSH"></div>
                                    {% else %}
                                        <div class="ball ball-inactive" aria-label="SSH"></div>
                                    {% endif %}
                                    <!-- HTTPS status -->
                                    {% if object.https_status == True %}
                                    <div class="ball ball-active" aria-label="HTTPS"></div>
                                    {% else %}
                                    <div class="ball ball-inactive" aria-label="HTTPS"></div>
                                    {% endif %}
                                </div>
                            {% endif %}

                            <div>
                                <input class="check-item collapse" type="checkbox">
                            </div>

                        </div>

                        <!-- Single model item header -->
                        <div class="model-item-header">
                            {% if object.ico %}
                                <img class="box-header-svg" src="/{{ object.get_ico_display }}" alt="switch">
                            {% endif %}
                            <div>
                                <h3><a href="{% url 'one'|create_url:model_view_url pk=object.pk %}">{{ object.name }}</a></h3>
                                <q>{% translate "Created" %}: {{ object.created }}</q></br>
                                <q>{% translate "Updated" %}: {{ object.updated }}</q>
                            </div>
                        </div>

                        <!-- Single model item body -->
                        <div class="model-item-body">
                            <table>
                                {% for row in display %}
                                    <tr>
                                        <th>{{ row|title }}:</th>
                                        <td>{{ object|key_value:row }}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>

                    </div>
                </div>
            {% endfor %}

        </div>

    {% else %}

        <!-- Table -->
        <div class="table grid-box">

            <table class="shadow table-hover table-blue">
                <thead>
                    <tr>
                        <th scope="col">{% translate "Name" %}</th>
                        <th scope="col">{% translate "Created" %}</th>
                        <th scope="col">{% translate "Updated" %}</th>
                        {% for row in display %}
                            <th scope="col">{{ row|title }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for object in objects %}
                        <tr>
                            <th><a href="{% url 'one'|create_url:model_view_url pk=object.pk %}">{{ object.name }}</a></th>
                            <td>{{ object.created }}</td>
                            <td>{{ object.updated }}</td>
                            {% for row in display %}
                                <td>{{ object|key_value:row }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>

    {% endif %}
    
{% endblock %}

App/templates/test.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load tags %}

{% block content %}

    {{ output }}
    
{% endblock %}